# Generated by Django 5.2.8 on 2025-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(help_text='Enter Prod Name', max_length=20)),
                ('Prod_ID', models.IntegerField(help_text='Enter Prod_id')),
                ('Prod_no', models.IntegerField(help_text='Enter the Product Number')),
            ],
        ),
    ]
